///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Example1.Repositories
{
    /// <summary>
    /// The class representing the Calculator element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "3.3.3")]
    [RepositoryFolder("5edecf32-9ef0-4d19-9f4e-a8ad7426c15e")]
    public partial class Calculator : RepoGenBaseFolder
    {
        static Calculator instance = new Calculator();
        CalculatorFolders.MainFormAppFolder _mainform;

        /// <summary>
        /// Gets the singleton class instance representing the Calculator element repository.
        /// </summary>
        [RepositoryFolder("5edecf32-9ef0-4d19-9f4e-a8ad7426c15e")]
        public static Calculator Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Calculator() 
            : base("Calculator", "", null, 30000, false, "5edecf32-9ef0-4d19-9f4e-a8ad7426c15e", ".\\RepositoryImages\\Calculator5edecf32.rximgres")
        {
            _mainform = new CalculatorFolders.MainFormAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The MainForm folder.
        /// </summary>
        [RepositoryFolder("6df0051a-f557-47f9-9fa6-ef9a6f73071f")]
        public virtual CalculatorFolders.MainFormAppFolder MainForm
        {
            get { return _mainform; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "3.3.3")]
    public partial class CalculatorFolders
    {
        /// <summary>
        /// The MainFormAppFolder folder.
        /// </summary>
        [RepositoryFolder("6df0051a-f557-47f9-9fa6-ef9a6f73071f")]
        public partial class MainFormAppFolder : RepoGenBaseFolder
        {
            CalculatorFolders.TitlebarFolder _titlebar;
            CalculatorFolders.MenubarFolder _menubar;
            CalculatorFolders.CalculatorFolder _calculator;
            RepoItemInfo _selfInfo;

            /// <summary>
            /// Creates a new MainForm  folder.
            /// </summary>
            public MainFormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MainForm", "/form[@class='CalcFrame']", parentFolder, 30000, true, "6df0051a-f557-47f9-9fa6-ef9a6f73071f", "")
            {
                _titlebar = new CalculatorFolders.TitlebarFolder(this);
                _menubar = new CalculatorFolders.MenubarFolder(this);
                _calculator = new CalculatorFolders.CalculatorFolder(this);
                _selfInfo = new RepoItemInfo(this, "Self", "", 0, null, "6df0051a-f557-47f9-9fa6-ef9a6f73071f");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("6df0051a-f557-47f9-9fa6-ef9a6f73071f")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("6df0051a-f557-47f9-9fa6-ef9a6f73071f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Titlebar folder.
            /// </summary>
            [RepositoryFolder("68444017-2c40-4899-b007-403bc57016ce")]
            public virtual CalculatorFolders.TitlebarFolder Titlebar
            {
                get { return _titlebar; }
            }

            /// <summary>
            /// The Menubar folder.
            /// </summary>
            [RepositoryFolder("1b145dfb-af19-4e49-b27d-4af3a04a30d1")]
            public virtual CalculatorFolders.MenubarFolder Menubar
            {
                get { return _menubar; }
            }

            /// <summary>
            /// The Calculator folder.
            /// </summary>
            [RepositoryFolder("33f308be-6c49-4a1f-a914-9d1374dc4baa")]
            public virtual CalculatorFolders.CalculatorFolder Calculator
            {
                get { return _calculator; }
            }
        }

        /// <summary>
        /// The TitlebarFolder folder.
        /// </summary>
        [RepositoryFolder("68444017-2c40-4899-b007-403bc57016ce")]
        public partial class TitlebarFolder : RepoGenBaseFolder
        {
            RepoItemInfo _selfInfo;
            RepoItemInfo _closebuttonInfo;
            RepoItemInfo _expandbuttonInfo;
            RepoItemInfo _collapsebuttonInfo;

            /// <summary>
            /// Creates a new Titlebar  folder.
            /// </summary>
            public TitlebarFolder(RepoGenBaseFolder parentFolder) :
                    base("Titlebar", "titlebar", parentFolder, 30000, true, "68444017-2c40-4899-b007-403bc57016ce", "")
            {
                _selfInfo = new RepoItemInfo(this, "Self", "", 0, null, "68444017-2c40-4899-b007-403bc57016ce");
                _closebuttonInfo = new RepoItemInfo(this, "CloseButton", "button[@accessiblename='Закрыть']", 30000, null, "2593a4e0-c5f8-402c-9126-20fe17f9b4ae");
                _expandbuttonInfo = new RepoItemInfo(this, "ExpandButton", "button[@accessiblename='Развернуть']", 30000, null, "91b139f0-b7f9-4b75-996f-3c7fb11ae489");
                _collapsebuttonInfo = new RepoItemInfo(this, "CollapseButton", "button[@accessiblename='Свернуть']", 30000, null, "a348ceb3-4285-4246-a16c-951815502934");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("68444017-2c40-4899-b007-403bc57016ce")]
            public virtual Ranorex.TitleBar Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.TitleBar>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("68444017-2c40-4899-b007-403bc57016ce")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The CloseButton item.
            /// </summary>
            [RepositoryItem("2593a4e0-c5f8-402c-9126-20fe17f9b4ae")]
            public virtual Ranorex.Button CloseButton
            {
                get
                {
                    return _closebuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The CloseButton item info.
            /// </summary>
            [RepositoryItemInfo("2593a4e0-c5f8-402c-9126-20fe17f9b4ae")]
            public virtual RepoItemInfo CloseButtonInfo
            {
                get
                {
                    return _closebuttonInfo;
                }
            }

            /// <summary>
            /// The ExpandButton item.
            /// </summary>
            [RepositoryItem("91b139f0-b7f9-4b75-996f-3c7fb11ae489")]
            public virtual Ranorex.Button ExpandButton
            {
                get
                {
                    return _expandbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ExpandButton item info.
            /// </summary>
            [RepositoryItemInfo("91b139f0-b7f9-4b75-996f-3c7fb11ae489")]
            public virtual RepoItemInfo ExpandButtonInfo
            {
                get
                {
                    return _expandbuttonInfo;
                }
            }

            /// <summary>
            /// The CollapseButton item.
            /// </summary>
            [RepositoryItem("a348ceb3-4285-4246-a16c-951815502934")]
            public virtual Ranorex.Button CollapseButton
            {
                get
                {
                    return _collapsebuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The CollapseButton item info.
            /// </summary>
            [RepositoryItemInfo("a348ceb3-4285-4246-a16c-951815502934")]
            public virtual RepoItemInfo CollapseButtonInfo
            {
                get
                {
                    return _collapsebuttonInfo;
                }
            }
        }

        /// <summary>
        /// The MenubarFolder folder.
        /// </summary>
        [RepositoryFolder("1b145dfb-af19-4e49-b27d-4af3a04a30d1")]
        public partial class MenubarFolder : RepoGenBaseFolder
        {
            RepoItemInfo _selfInfo;
            RepoItemInfo _viewbuttonInfo;
            RepoItemInfo _correctionbuttonInfo;
            RepoItemInfo _informationbuttonInfo;

            /// <summary>
            /// Creates a new Menubar  folder.
            /// </summary>
            public MenubarFolder(RepoGenBaseFolder parentFolder) :
                    base("Menubar", "menubar[@accessiblename='Приложение']", parentFolder, 30000, true, "1b145dfb-af19-4e49-b27d-4af3a04a30d1", "")
            {
                _selfInfo = new RepoItemInfo(this, "Self", "", 0, null, "1b145dfb-af19-4e49-b27d-4af3a04a30d1");
                _viewbuttonInfo = new RepoItemInfo(this, "ViewButton", "menuitem[@accessiblename='Вид']", 30000, null, "77be3b48-87e6-4ff3-808a-bf196d64a7ab");
                _correctionbuttonInfo = new RepoItemInfo(this, "CorrectionButton", "menuitem[@accessiblename='Правка']", 30000, null, "39c4cce2-b818-41eb-a728-cdf56818ccd2");
                _informationbuttonInfo = new RepoItemInfo(this, "InformationButton", "menuitem[@accessiblename='Справка']", 30000, null, "7465779d-1572-4c0d-9737-676a4595d42d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("1b145dfb-af19-4e49-b27d-4af3a04a30d1")]
            public virtual Ranorex.MenuBar Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MenuBar>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("1b145dfb-af19-4e49-b27d-4af3a04a30d1")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ViewButton item.
            /// </summary>
            [RepositoryItem("77be3b48-87e6-4ff3-808a-bf196d64a7ab")]
            public virtual Ranorex.MenuItem ViewButton
            {
                get
                {
                    return _viewbuttonInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The ViewButton item info.
            /// </summary>
            [RepositoryItemInfo("77be3b48-87e6-4ff3-808a-bf196d64a7ab")]
            public virtual RepoItemInfo ViewButtonInfo
            {
                get
                {
                    return _viewbuttonInfo;
                }
            }

            /// <summary>
            /// The CorrectionButton item.
            /// </summary>
            [RepositoryItem("39c4cce2-b818-41eb-a728-cdf56818ccd2")]
            public virtual Ranorex.MenuItem CorrectionButton
            {
                get
                {
                    return _correctionbuttonInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The CorrectionButton item info.
            /// </summary>
            [RepositoryItemInfo("39c4cce2-b818-41eb-a728-cdf56818ccd2")]
            public virtual RepoItemInfo CorrectionButtonInfo
            {
                get
                {
                    return _correctionbuttonInfo;
                }
            }

            /// <summary>
            /// The InformationButton item.
            /// </summary>
            [RepositoryItem("7465779d-1572-4c0d-9737-676a4595d42d")]
            public virtual Ranorex.MenuItem InformationButton
            {
                get
                {
                    return _informationbuttonInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The InformationButton item info.
            /// </summary>
            [RepositoryItemInfo("7465779d-1572-4c0d-9737-676a4595d42d")]
            public virtual RepoItemInfo InformationButtonInfo
            {
                get
                {
                    return _informationbuttonInfo;
                }
            }
        }

        /// <summary>
        /// The CalculatorFolder folder.
        /// </summary>
        [RepositoryFolder("33f308be-6c49-4a1f-a914-9d1374dc4baa")]
        public partial class CalculatorFolder : RepoGenBaseFolder
        {
            RepoItemInfo _selfInfo;
            RepoItemInfo _resultinputInfo;
            RepoItemInfo _mcbuttonInfo;
            RepoItemInfo _backspacebuttonInfo;
            RepoItemInfo _n7buttonInfo;
            RepoItemInfo _n4buttonInfo;
            RepoItemInfo _n1buttonInfo;
            RepoItemInfo _n0buttonInfo;
            RepoItemInfo _mrbuttonInfo;
            RepoItemInfo _cebuttonInfo;
            RepoItemInfo _n8buttonInfo;
            RepoItemInfo _n5buttonInfo;
            RepoItemInfo _n2buttonInfo;
            RepoItemInfo _msbuttonInfo;
            RepoItemInfo _cbuttonInfo;
            RepoItemInfo _n9buttonInfo;
            RepoItemInfo _n6buttonInfo;
            RepoItemInfo _n3buttonInfo;
            RepoItemInfo _decimalseparatorbuttonInfo;
            RepoItemInfo _mplusbuttonInfo;
            RepoItemInfo _plusminusbuttonInfo;
            RepoItemInfo _divisionbuttonInfo;
            RepoItemInfo _multiplicationbuttonInfo;
            RepoItemInfo _subtractionbuttonInfo;
            RepoItemInfo _additionbuttonInfo;
            RepoItemInfo _mminusbuttonInfo;
            RepoItemInfo _squarerootbuttonInfo;
            RepoItemInfo _percentbuttonInfo;
            RepoItemInfo _reciprocalbuttonInfo;
            RepoItemInfo _equallybuttonInfo;

            /// <summary>
            /// Creates a new Calculator  folder.
            /// </summary>
            public CalculatorFolder(RepoGenBaseFolder parentFolder) :
                    base("Calculator", "element[@class='CalcFrame']", parentFolder, 30000, true, "33f308be-6c49-4a1f-a914-9d1374dc4baa", "")
            {
                _selfInfo = new RepoItemInfo(this, "Self", "", 0, null, "33f308be-6c49-4a1f-a914-9d1374dc4baa");
                _resultinputInfo = new RepoItemInfo(this, "ResultInput", "container[@windowextendedstyle~'ToolWindow']/text[@windowtext!='']", 30000, null, "ef8e2b51-dca9-4d76-b52c-b8a6ec2be16b");
                _mcbuttonInfo = new RepoItemInfo(this, "MCButton", ".//button[@accessiblename='Очистка памяти']", 30000, null, "237902d6-a3f9-4d29-b573-4e09f19dee31");
                _backspacebuttonInfo = new RepoItemInfo(this, "BackspaceButton", ".//button[@accessiblename='Backspace']", 30000, null, "c3ee237c-3499-4d03-bc40-961108ce44df");
                _n7buttonInfo = new RepoItemInfo(this, "N7Button", ".//button[@accessiblename='7']", 30000, null, "9d6cbc5b-135c-4d70-be9e-337230ce6d67");
                _n4buttonInfo = new RepoItemInfo(this, "N4Button", ".//button[@accessiblename='4']", 30000, null, "61bea1b2-71b9-4c31-999f-0b45337e2670");
                _n1buttonInfo = new RepoItemInfo(this, "N1Button", ".//button[@accessiblename='1']", 30000, null, "1e421129-268e-4af7-a763-7d2c1b9ce0b9");
                _n0buttonInfo = new RepoItemInfo(this, "N0Button", ".//button[@accessiblename='0']", 30000, null, "e888eeed-02f1-42e7-aa86-4ec00508adec");
                _mrbuttonInfo = new RepoItemInfo(this, "MRButton", ".//button[@accessiblename='Вызов из памяти']", 30000, null, "47b51ec1-6153-419c-b6b6-786c6a24f54f");
                _cebuttonInfo = new RepoItemInfo(this, "CEButton", ".//button[@accessiblename='Очистка записи']", 30000, null, "2af6023b-593d-4bc7-ad7e-02f182dd2c82");
                _n8buttonInfo = new RepoItemInfo(this, "N8Button", ".//button[@accessiblename='8']", 30000, null, "b9275f55-a908-4639-9487-f3136dfa3a08");
                _n5buttonInfo = new RepoItemInfo(this, "N5Button", ".//button[@accessiblename='5']", 30000, null, "6d54b3d0-a8ac-41fe-9aaa-7e1d6ffac5aa");
                _n2buttonInfo = new RepoItemInfo(this, "N2Button", ".//button[@accessiblename='2']", 30000, null, "2f885d89-c825-449a-96e8-9f0ddafc2eee");
                _msbuttonInfo = new RepoItemInfo(this, "MSButton", ".//button[@accessiblename='Сохранение в памяти']", 30000, null, "5722a027-a98f-437a-838b-04008e9d306d");
                _cbuttonInfo = new RepoItemInfo(this, "CButton", ".//button[@accessiblename='Очистить']", 30000, null, "ee27716d-cae3-4f13-96a5-b5d7c8d70562");
                _n9buttonInfo = new RepoItemInfo(this, "N9Button", ".//button[@accessiblename='9']", 30000, null, "2b366382-40b9-40a8-89a0-13a0bbe17004");
                _n6buttonInfo = new RepoItemInfo(this, "N6Button", ".//button[@accessiblename='6']", 30000, null, "d5dd637c-caeb-49e3-8c83-a843705d8845");
                _n3buttonInfo = new RepoItemInfo(this, "N3Button", ".//button[@accessiblename='3']", 30000, null, "88a71068-45b3-420e-9a32-71019e312ea4");
                _decimalseparatorbuttonInfo = new RepoItemInfo(this, "DecimalSeparatorButton", ".//button[@accessiblename='Десятичный разделитель']", 30000, null, "391852a4-519f-48b8-9f50-8295243b6a37");
                _mplusbuttonInfo = new RepoItemInfo(this, "MPlusButton", ".//button[@accessiblename='Добавление памяти']", 30000, null, "2905ca60-9865-4f01-9e87-f3c5932b27e6");
                _plusminusbuttonInfo = new RepoItemInfo(this, "PlusMinusButton", ".//button[@accessiblename='Унарный минус']", 30000, null, "ad0d9f24-f53e-4c09-b1f4-24a246bed717");
                _divisionbuttonInfo = new RepoItemInfo(this, "DivisionButton", ".//button[@accessiblename='Деление']", 30000, null, "0e728110-5cef-4fde-becd-d5b22c20c107");
                _multiplicationbuttonInfo = new RepoItemInfo(this, "MultiplicationButton", ".//button[@accessiblename='Умножение']", 30000, null, "d3a3938b-5517-42d1-a5c7-52129e9d4242");
                _subtractionbuttonInfo = new RepoItemInfo(this, "SubtractionButton", ".//button[@accessiblename='Вычитание']", 30000, null, "61d1aaad-fcf3-467d-9479-f2c7cca6a79f");
                _additionbuttonInfo = new RepoItemInfo(this, "AdditionButton", ".//button[@accessiblename='Сложение']", 30000, null, "7b897f38-0ff3-476a-8e37-300c49bfeb43");
                _mminusbuttonInfo = new RepoItemInfo(this, "MMinusButton", ".//button[@accessiblename='Вычитание памяти']", 30000, null, "4e822ec6-bb36-4cf2-a756-7363ebe10141");
                _squarerootbuttonInfo = new RepoItemInfo(this, "SquareRootButton", ".//button[@accessiblename='Квадратный корень']", 30000, null, "bcfe3d5f-3bce-4e8f-8cac-42022be1bfaf");
                _percentbuttonInfo = new RepoItemInfo(this, "PercentButton", ".//button[@accessiblename='Процент']", 30000, null, "f5bc3be4-2902-4cd9-a095-a2a8a29563b0");
                _reciprocalbuttonInfo = new RepoItemInfo(this, "ReciprocalButton", ".//button[@accessiblename='Обратная величина']", 30000, null, "68573099-52eb-4853-b45e-a2641e6e6bf0");
                _equallybuttonInfo = new RepoItemInfo(this, "EquallyButton", ".//button[@accessiblename='Равно']", 30000, null, "5bb1d296-a858-46dd-a8d1-db7f956e5896");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("33f308be-6c49-4a1f-a914-9d1374dc4baa")]
            public virtual Ranorex.Unknown Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("33f308be-6c49-4a1f-a914-9d1374dc4baa")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ResultInput item.
            /// </summary>
            [RepositoryItem("ef8e2b51-dca9-4d76-b52c-b8a6ec2be16b")]
            public virtual Ranorex.Text ResultInput
            {
                get
                {
                    return _resultinputInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ResultInput item info.
            /// </summary>
            [RepositoryItemInfo("ef8e2b51-dca9-4d76-b52c-b8a6ec2be16b")]
            public virtual RepoItemInfo ResultInputInfo
            {
                get
                {
                    return _resultinputInfo;
                }
            }

            /// <summary>
            /// The MCButton item.
            /// </summary>
            [RepositoryItem("237902d6-a3f9-4d29-b573-4e09f19dee31")]
            public virtual Ranorex.Button MCButton
            {
                get
                {
                    return _mcbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The MCButton item info.
            /// </summary>
            [RepositoryItemInfo("237902d6-a3f9-4d29-b573-4e09f19dee31")]
            public virtual RepoItemInfo MCButtonInfo
            {
                get
                {
                    return _mcbuttonInfo;
                }
            }

            /// <summary>
            /// The BackspaceButton item.
            /// </summary>
            [RepositoryItem("c3ee237c-3499-4d03-bc40-961108ce44df")]
            public virtual Ranorex.Button BackspaceButton
            {
                get
                {
                    return _backspacebuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BackspaceButton item info.
            /// </summary>
            [RepositoryItemInfo("c3ee237c-3499-4d03-bc40-961108ce44df")]
            public virtual RepoItemInfo BackspaceButtonInfo
            {
                get
                {
                    return _backspacebuttonInfo;
                }
            }

            /// <summary>
            /// The N7Button item.
            /// </summary>
            [RepositoryItem("9d6cbc5b-135c-4d70-be9e-337230ce6d67")]
            public virtual Ranorex.Button N7Button
            {
                get
                {
                    return _n7buttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The N7Button item info.
            /// </summary>
            [RepositoryItemInfo("9d6cbc5b-135c-4d70-be9e-337230ce6d67")]
            public virtual RepoItemInfo N7ButtonInfo
            {
                get
                {
                    return _n7buttonInfo;
                }
            }

            /// <summary>
            /// The N4Button item.
            /// </summary>
            [RepositoryItem("61bea1b2-71b9-4c31-999f-0b45337e2670")]
            public virtual Ranorex.Button N4Button
            {
                get
                {
                    return _n4buttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The N4Button item info.
            /// </summary>
            [RepositoryItemInfo("61bea1b2-71b9-4c31-999f-0b45337e2670")]
            public virtual RepoItemInfo N4ButtonInfo
            {
                get
                {
                    return _n4buttonInfo;
                }
            }

            /// <summary>
            /// The N1Button item.
            /// </summary>
            [RepositoryItem("1e421129-268e-4af7-a763-7d2c1b9ce0b9")]
            public virtual Ranorex.Button N1Button
            {
                get
                {
                    return _n1buttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The N1Button item info.
            /// </summary>
            [RepositoryItemInfo("1e421129-268e-4af7-a763-7d2c1b9ce0b9")]
            public virtual RepoItemInfo N1ButtonInfo
            {
                get
                {
                    return _n1buttonInfo;
                }
            }

            /// <summary>
            /// The N0Button item.
            /// </summary>
            [RepositoryItem("e888eeed-02f1-42e7-aa86-4ec00508adec")]
            public virtual Ranorex.Button N0Button
            {
                get
                {
                    return _n0buttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The N0Button item info.
            /// </summary>
            [RepositoryItemInfo("e888eeed-02f1-42e7-aa86-4ec00508adec")]
            public virtual RepoItemInfo N0ButtonInfo
            {
                get
                {
                    return _n0buttonInfo;
                }
            }

            /// <summary>
            /// The MRButton item.
            /// </summary>
            [RepositoryItem("47b51ec1-6153-419c-b6b6-786c6a24f54f")]
            public virtual Ranorex.Button MRButton
            {
                get
                {
                    return _mrbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The MRButton item info.
            /// </summary>
            [RepositoryItemInfo("47b51ec1-6153-419c-b6b6-786c6a24f54f")]
            public virtual RepoItemInfo MRButtonInfo
            {
                get
                {
                    return _mrbuttonInfo;
                }
            }

            /// <summary>
            /// The CEButton item.
            /// </summary>
            [RepositoryItem("2af6023b-593d-4bc7-ad7e-02f182dd2c82")]
            public virtual Ranorex.Button CEButton
            {
                get
                {
                    return _cebuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The CEButton item info.
            /// </summary>
            [RepositoryItemInfo("2af6023b-593d-4bc7-ad7e-02f182dd2c82")]
            public virtual RepoItemInfo CEButtonInfo
            {
                get
                {
                    return _cebuttonInfo;
                }
            }

            /// <summary>
            /// The N8Button item.
            /// </summary>
            [RepositoryItem("b9275f55-a908-4639-9487-f3136dfa3a08")]
            public virtual Ranorex.Button N8Button
            {
                get
                {
                    return _n8buttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The N8Button item info.
            /// </summary>
            [RepositoryItemInfo("b9275f55-a908-4639-9487-f3136dfa3a08")]
            public virtual RepoItemInfo N8ButtonInfo
            {
                get
                {
                    return _n8buttonInfo;
                }
            }

            /// <summary>
            /// The N5Button item.
            /// </summary>
            [RepositoryItem("6d54b3d0-a8ac-41fe-9aaa-7e1d6ffac5aa")]
            public virtual Ranorex.Button N5Button
            {
                get
                {
                    return _n5buttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The N5Button item info.
            /// </summary>
            [RepositoryItemInfo("6d54b3d0-a8ac-41fe-9aaa-7e1d6ffac5aa")]
            public virtual RepoItemInfo N5ButtonInfo
            {
                get
                {
                    return _n5buttonInfo;
                }
            }

            /// <summary>
            /// The N2Button item.
            /// </summary>
            [RepositoryItem("2f885d89-c825-449a-96e8-9f0ddafc2eee")]
            public virtual Ranorex.Button N2Button
            {
                get
                {
                    return _n2buttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The N2Button item info.
            /// </summary>
            [RepositoryItemInfo("2f885d89-c825-449a-96e8-9f0ddafc2eee")]
            public virtual RepoItemInfo N2ButtonInfo
            {
                get
                {
                    return _n2buttonInfo;
                }
            }

            /// <summary>
            /// The MSButton item.
            /// </summary>
            [RepositoryItem("5722a027-a98f-437a-838b-04008e9d306d")]
            public virtual Ranorex.Button MSButton
            {
                get
                {
                    return _msbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The MSButton item info.
            /// </summary>
            [RepositoryItemInfo("5722a027-a98f-437a-838b-04008e9d306d")]
            public virtual RepoItemInfo MSButtonInfo
            {
                get
                {
                    return _msbuttonInfo;
                }
            }

            /// <summary>
            /// The CButton item.
            /// </summary>
            [RepositoryItem("ee27716d-cae3-4f13-96a5-b5d7c8d70562")]
            public virtual Ranorex.Button CButton
            {
                get
                {
                    return _cbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The CButton item info.
            /// </summary>
            [RepositoryItemInfo("ee27716d-cae3-4f13-96a5-b5d7c8d70562")]
            public virtual RepoItemInfo CButtonInfo
            {
                get
                {
                    return _cbuttonInfo;
                }
            }

            /// <summary>
            /// The N9Button item.
            /// </summary>
            [RepositoryItem("2b366382-40b9-40a8-89a0-13a0bbe17004")]
            public virtual Ranorex.Button N9Button
            {
                get
                {
                    return _n9buttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The N9Button item info.
            /// </summary>
            [RepositoryItemInfo("2b366382-40b9-40a8-89a0-13a0bbe17004")]
            public virtual RepoItemInfo N9ButtonInfo
            {
                get
                {
                    return _n9buttonInfo;
                }
            }

            /// <summary>
            /// The N6Button item.
            /// </summary>
            [RepositoryItem("d5dd637c-caeb-49e3-8c83-a843705d8845")]
            public virtual Ranorex.Button N6Button
            {
                get
                {
                    return _n6buttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The N6Button item info.
            /// </summary>
            [RepositoryItemInfo("d5dd637c-caeb-49e3-8c83-a843705d8845")]
            public virtual RepoItemInfo N6ButtonInfo
            {
                get
                {
                    return _n6buttonInfo;
                }
            }

            /// <summary>
            /// The N3Button item.
            /// </summary>
            [RepositoryItem("88a71068-45b3-420e-9a32-71019e312ea4")]
            public virtual Ranorex.Button N3Button
            {
                get
                {
                    return _n3buttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The N3Button item info.
            /// </summary>
            [RepositoryItemInfo("88a71068-45b3-420e-9a32-71019e312ea4")]
            public virtual RepoItemInfo N3ButtonInfo
            {
                get
                {
                    return _n3buttonInfo;
                }
            }

            /// <summary>
            /// The DecimalSeparatorButton item.
            /// </summary>
            [RepositoryItem("391852a4-519f-48b8-9f50-8295243b6a37")]
            public virtual Ranorex.Button DecimalSeparatorButton
            {
                get
                {
                    return _decimalseparatorbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The DecimalSeparatorButton item info.
            /// </summary>
            [RepositoryItemInfo("391852a4-519f-48b8-9f50-8295243b6a37")]
            public virtual RepoItemInfo DecimalSeparatorButtonInfo
            {
                get
                {
                    return _decimalseparatorbuttonInfo;
                }
            }

            /// <summary>
            /// The MPlusButton item.
            /// </summary>
            [RepositoryItem("2905ca60-9865-4f01-9e87-f3c5932b27e6")]
            public virtual Ranorex.Button MPlusButton
            {
                get
                {
                    return _mplusbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The MPlusButton item info.
            /// </summary>
            [RepositoryItemInfo("2905ca60-9865-4f01-9e87-f3c5932b27e6")]
            public virtual RepoItemInfo MPlusButtonInfo
            {
                get
                {
                    return _mplusbuttonInfo;
                }
            }

            /// <summary>
            /// The PlusMinusButton item.
            /// </summary>
            [RepositoryItem("ad0d9f24-f53e-4c09-b1f4-24a246bed717")]
            public virtual Ranorex.Button PlusMinusButton
            {
                get
                {
                    return _plusminusbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The PlusMinusButton item info.
            /// </summary>
            [RepositoryItemInfo("ad0d9f24-f53e-4c09-b1f4-24a246bed717")]
            public virtual RepoItemInfo PlusMinusButtonInfo
            {
                get
                {
                    return _plusminusbuttonInfo;
                }
            }

            /// <summary>
            /// The DivisionButton item.
            /// </summary>
            [RepositoryItem("0e728110-5cef-4fde-becd-d5b22c20c107")]
            public virtual Ranorex.Button DivisionButton
            {
                get
                {
                    return _divisionbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The DivisionButton item info.
            /// </summary>
            [RepositoryItemInfo("0e728110-5cef-4fde-becd-d5b22c20c107")]
            public virtual RepoItemInfo DivisionButtonInfo
            {
                get
                {
                    return _divisionbuttonInfo;
                }
            }

            /// <summary>
            /// The MultiplicationButton item.
            /// </summary>
            [RepositoryItem("d3a3938b-5517-42d1-a5c7-52129e9d4242")]
            public virtual Ranorex.Button MultiplicationButton
            {
                get
                {
                    return _multiplicationbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The MultiplicationButton item info.
            /// </summary>
            [RepositoryItemInfo("d3a3938b-5517-42d1-a5c7-52129e9d4242")]
            public virtual RepoItemInfo MultiplicationButtonInfo
            {
                get
                {
                    return _multiplicationbuttonInfo;
                }
            }

            /// <summary>
            /// The SubtractionButton item.
            /// </summary>
            [RepositoryItem("61d1aaad-fcf3-467d-9479-f2c7cca6a79f")]
            public virtual Ranorex.Button SubtractionButton
            {
                get
                {
                    return _subtractionbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The SubtractionButton item info.
            /// </summary>
            [RepositoryItemInfo("61d1aaad-fcf3-467d-9479-f2c7cca6a79f")]
            public virtual RepoItemInfo SubtractionButtonInfo
            {
                get
                {
                    return _subtractionbuttonInfo;
                }
            }

            /// <summary>
            /// The AdditionButton item.
            /// </summary>
            [RepositoryItem("7b897f38-0ff3-476a-8e37-300c49bfeb43")]
            public virtual Ranorex.Button AdditionButton
            {
                get
                {
                    return _additionbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The AdditionButton item info.
            /// </summary>
            [RepositoryItemInfo("7b897f38-0ff3-476a-8e37-300c49bfeb43")]
            public virtual RepoItemInfo AdditionButtonInfo
            {
                get
                {
                    return _additionbuttonInfo;
                }
            }

            /// <summary>
            /// The MMinusButton item.
            /// </summary>
            [RepositoryItem("4e822ec6-bb36-4cf2-a756-7363ebe10141")]
            public virtual Ranorex.Button MMinusButton
            {
                get
                {
                    return _mminusbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The MMinusButton item info.
            /// </summary>
            [RepositoryItemInfo("4e822ec6-bb36-4cf2-a756-7363ebe10141")]
            public virtual RepoItemInfo MMinusButtonInfo
            {
                get
                {
                    return _mminusbuttonInfo;
                }
            }

            /// <summary>
            /// The SquareRootButton item.
            /// </summary>
            [RepositoryItem("bcfe3d5f-3bce-4e8f-8cac-42022be1bfaf")]
            public virtual Ranorex.Button SquareRootButton
            {
                get
                {
                    return _squarerootbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The SquareRootButton item info.
            /// </summary>
            [RepositoryItemInfo("bcfe3d5f-3bce-4e8f-8cac-42022be1bfaf")]
            public virtual RepoItemInfo SquareRootButtonInfo
            {
                get
                {
                    return _squarerootbuttonInfo;
                }
            }

            /// <summary>
            /// The PercentButton item.
            /// </summary>
            [RepositoryItem("f5bc3be4-2902-4cd9-a095-a2a8a29563b0")]
            public virtual Ranorex.Button PercentButton
            {
                get
                {
                    return _percentbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The PercentButton item info.
            /// </summary>
            [RepositoryItemInfo("f5bc3be4-2902-4cd9-a095-a2a8a29563b0")]
            public virtual RepoItemInfo PercentButtonInfo
            {
                get
                {
                    return _percentbuttonInfo;
                }
            }

            /// <summary>
            /// The ReciprocalButton item.
            /// </summary>
            [RepositoryItem("68573099-52eb-4853-b45e-a2641e6e6bf0")]
            public virtual Ranorex.Button ReciprocalButton
            {
                get
                {
                    return _reciprocalbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ReciprocalButton item info.
            /// </summary>
            [RepositoryItemInfo("68573099-52eb-4853-b45e-a2641e6e6bf0")]
            public virtual RepoItemInfo ReciprocalButtonInfo
            {
                get
                {
                    return _reciprocalbuttonInfo;
                }
            }

            /// <summary>
            /// The EquallyButton item.
            /// </summary>
            [RepositoryItem("5bb1d296-a858-46dd-a8d1-db7f956e5896")]
            public virtual Ranorex.Button EquallyButton
            {
                get
                {
                    return _equallybuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The EquallyButton item info.
            /// </summary>
            [RepositoryItemInfo("5bb1d296-a858-46dd-a8d1-db7f956e5896")]
            public virtual RepoItemInfo EquallyButtonInfo
            {
                get
                {
                    return _equallybuttonInfo;
                }
            }
        }

    }
}